EOL_Zooarchaeology_Metrics_Dataset_Version_2.csv:data-make.R
	mkdir -p ../data
	curl 'https://artiraq.org/static/opencontext/revised-tables/def8fb9c9d7fdc1993db45b7350ca955.csv' -A "Mozilla/5.0" -o $@
	Rscript --vanilla 'data-make.R'
